[build]
  functions = "functions"

[[redirects]]
  from = "/api/books"
  to = "/.netlify/functions/get"
  status = 200
  force = true

[[redirects]]
  from = "/api/books/add"
  to = "/.netlify/functions/post"
  status = 200
  method = "POST"
  force = true
  
[[redirects]]
  from = "/api/books/edit"
  to = "/.netlify/functions/put"
  status = 200
  method = "PUT"
  force = true

[[redirects]]
  from = "/api/books/delete"
  to = "/.netlify/functions/delete"
  status = 200
  force = true
  method = "DELETE"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  force = true

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200
  force = true

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200
  force = true

